name: Three Card Poker CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main] 
jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run JUnit 5 unit tests
        run: mvn test
  api-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:  
          java-version: '17'
          distribution: 'temurin'

      - name: Start Spring Boot App
        run: mvn spring-boot:run &
      - name: wait for app to start
        run: sleep 20

      - name: Run RestAssured API Tests
        run: mvn test -Dtest=DealApiTest, EvaluateApiNegativeTest, EvaluateApiTest

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: target/suirefire-reports/